Repository arduino/crossbuild, pull requests merged in 2022-08, with the labels that each got.

#3 Add CI workflow to synchronize with shared repository labels
  .github/workflows/sync-labels.yml
  README.md
Labels: enhancement

#4 Add CI workflow to check Markdown files for problems
  .github/workflows/check-markdown-task.yml
  .gitignore
  .markdown-link-check.json
  .markdownlint.yml
  .markdownlintignore
  README.md
  Taskfile.yml
  deps/eudev-3.2.10/README.md
  deps/hidapi-0.12.0/BUILD.cmake.md
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#5 Create LICENSE.txt
  LICENSE.txt
Labels: type: enhancement

#6 Add CI workflow to check the license file
  .github/workflows/check-license.yml
  README.md
Labels: type: enhancement, topic: infrastructure

#7 Add CI workflow to validate Taskfiles
  .github/workflows/check-taskfiles.yml
  README.md
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure
